/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as DashboardTreasurerRouteImport } from './routes/dashboard.treasurer'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardMemberRouteImport } from './routes/dashboard.member'
import { Route as DashboardLoansRouteImport } from './routes/dashboard.loans'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as ApiPublicPayheroWebhookRouteImport } from './routes/api/public/payhero-webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTreasurerRoute = DashboardTreasurerRouteImport.update({
  id: '/treasurer',
  path: '/treasurer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemberRoute = DashboardMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoansRoute = DashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicPayheroWebhookRoute = ApiPublicPayheroWebhookRouteImport.update({
  id: '/api/public/payhero-webhook',
  path: '/api/public/payhero-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/member': typeof DashboardMemberRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/treasurer': typeof DashboardTreasurerRoute
  '/join/$token': typeof JoinTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/payhero-webhook': typeof ApiPublicPayheroWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/member': typeof DashboardMemberRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/treasurer': typeof DashboardTreasurerRoute
  '/join/$token': typeof JoinTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/payhero-webhook': typeof ApiPublicPayheroWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/member': typeof DashboardMemberRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/treasurer': typeof DashboardTreasurerRoute
  '/join/$token': typeof JoinTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/payhero-webhook': typeof ApiPublicPayheroWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/campaigns'
    | '/dashboard/import'
    | '/dashboard/loans'
    | '/dashboard/member'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/dashboard/treasurer'
    | '/join/$token'
    | '/dashboard/'
    | '/api/public/payhero-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/campaigns'
    | '/dashboard/import'
    | '/dashboard/loans'
    | '/dashboard/member'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/dashboard/treasurer'
    | '/join/$token'
    | '/dashboard'
    | '/api/public/payhero-webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/campaigns'
    | '/dashboard/import'
    | '/dashboard/loans'
    | '/dashboard/member'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/dashboard/treasurer'
    | '/join/$token'
    | '/dashboard/'
    | '/api/public/payhero-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiPublicPayheroWebhookRoute: typeof ApiPublicPayheroWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/treasurer': {
      id: '/dashboard/treasurer'
      path: '/treasurer'
      fullPath: '/dashboard/treasurer'
      preLoaderRoute: typeof DashboardTreasurerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/member': {
      id: '/dashboard/member'
      path: '/member'
      fullPath: '/dashboard/member'
      preLoaderRoute: typeof DashboardMemberRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/loans': {
      id: '/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof DashboardLoansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/payhero-webhook': {
      id: '/api/public/payhero-webhook'
      path: '/api/public/payhero-webhook'
      fullPath: '/api/public/payhero-webhook'
      preLoaderRoute: typeof ApiPublicPayheroWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardLoansRoute: typeof DashboardLoansRoute
  DashboardMemberRoute: typeof DashboardMemberRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTreasurerRoute: typeof DashboardTreasurerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardLoansRoute: DashboardLoansRoute,
  DashboardMemberRoute: DashboardMemberRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTreasurerRoute: DashboardTreasurerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiPublicPayheroWebhookRoute: ApiPublicPayheroWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
